version: '3.7'

services:
    sensor-service:
        build: ./sensor-service
        image: piwa/thermometer.sensor-service
        ports:
            - "8081:8080"       
        environment:
            - SPRING_PROFILES_ACTIVE=dev,dev_docker_compose         
        secrets:
            - aws_credentials    
    temperature-service:
        build: ./temperature-service
        image: piwa/thermometer.temperature-service
        ports:
            - "8082:8080"        
        environment:
            - SPRING_PROFILES_ACTIVE=dev,dev_docker_compose            
        secrets:
            - aws_credentials
    frontend-service:
        build: ./frontend-service
        image: piwa/thermometer.frontend-service
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=dev,dev_docker_compose            
            
       
secrets:
   aws_credentials:
     file: aws_credentials