package at.piwa.thermometer.sensorservice.database;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Created by philippwaibel on 18/01/16.
 */
@Data
@DynamoDBTable(tableName = "Sensors")
public class Sensor {

    @DynamoDBHashKey(attributeName = "SensorID")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "Name")
    private String name;

    @DynamoDBAttribute(attributeName = "Type")
    private String type;

    @DynamoDBAttribute(attributeName = "Description")
    private String description;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "SensorConnection")
    private SensorConnection sensorConnection;

    @DynamoDBAttribute(attributeName = "HardwareID")
    private String hardwareID;

}
